[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "explorer"
version = "0.0.0"
requires-python = ">=3.12"

[tool.maturin]
manifest-path = "crates/core/Cargo.toml"
module-name = "core"

